### ISSUE TITLE
Add a section about Lambda's and Exceptions

### ISSUE THREAD

**Issue by schmitch** [winterbe/java8-tutorial#11]
Hello, currently when using Lambda's on Functions that throw an Exception, they should be wrapped inside the Lambda, also type interference doesn't know that there will be an Exception on Compile Time, so it will be thrown on Runtime.

**Comment by winterbe** [comment]
Checked Exceptions are indeed a problem when working with lambda expressions. You have to catch every possible checked exception inside lambda expressions, which makes code kinda verbose.

However I have to plans to add such information to my guide currently.
