### ISSUE TITLE
map.merge bug

### ISSUE THREAD

**Issue by justinmk** [winterbe/java8-tutorial#13]
```
map.merge(9, "val9", (value, newValue) -> value.concat(newValue));
map.get(9);             // val9

map.merge(9, "concat", (value, newValue) -> value.concat(newValue));
map.get(9);             // val9concat
```

The first comment should be `val9val9` and the last comment should be `val9val9concat`. Unless I made a mistake in following along.

**Comment by winterbe** [comment]
Take a look at the example above. The entry for key `9` is removed from the map in these lines:

```java
map.computeIfPresent(9, (num, val) -> null);
map.containsKey(9);     // false
```

That's the reason that `merge` initially puts `val9` under key `9` into the map.

Without removing the entry beforehand, your assumption would be absolutely correct!
