### ISSUE TITLE
Some may be redundant

### ISSUE THREAD

**Issue by poetix** [winterbe/java8-tutorial#2]
As I understand from your blog post, the purpose of the Some class is to simplify

```java
Optional.ofNullable(maybeBean)
  .flatMap(bean -> optional.ofNullable(bean.getSprout()))
  .flatMap(sprout -> optional.ofNullable(sprout.getFoo()))
  .orElse("foo not found");
```

However, Optional.map *already* handles nulls in the way you want:

```java
Optional.ofNullable(maybeBean)
  .map(Bean::getSprout)
  .map(Sprout::getFoo)
  .orElse("foo not found")
```

This is because "map" automatically converts null values to Optional.empty(). (I had assumed, as I think you have, that the above code would throw NullPointerExceptions if getSprout() returned null. But this is not in fact the case).

**Comment by winterbe** [comment]
Thanks for your feedback. You're absolutely right. I've already updated the blog post and will change the example code in this repo as well later.

I'm glad this works out of the box without the need to write a legacy helper class.
