### ISSUE TITLE
Annotations not work in Android

### ISSUE THREAD

**Issue by archerLj** [winterbe/java8-tutorial#36]
[Annotations1.java](https://github.com/winterbe/java8-tutorial/blob/master/src/com/winterbe/java8/samples/misc/Annotations1.java)

```
        Hint hint = Person.class.getAnnotation(Hint.class);
        System.out.println(hint);   // null

        Hints hints1 = Person.class.getAnnotation(Hints.class);
        System.out.println(hints1.value().length);  // null

        Hint[] hints2 = Person.class.getAnnotationsByType(Hint.class);
        System.out.println(hints2.length);  // null
```
`hint`, `hints1` and `hints2` always be `null` in Android Studio 3.0.1.

Do u know why?

**Comment by winterbe** [comment]
Last time I used Android it was still stuck on Java 6. So you cannot use
Java 8 features on Android yet. I recommend Kotlin for Android development.
It’s superior to Java 8 in many ways.

archerLj <notifications@github.com> schrieb am Fr. 22. Dez. 2017 um 10:12:
