### ISSUE TITLE
Ambiguous formulation in the first paragraph of Functional Interfaces

### ISSUE THREAD

**Issue by clehene** [winterbe/java8-tutorial#5]
> How does lambda expressions fit into Javas type system? Each lambda corresponds to a given type, specified by an interface. A so called functional interface must contain exactly one abstract method declaration.

It's not immediately clear from the context why this starts with lambda expressions and the second phrase about "each corresponds to a given type" is ambiguous 
> A functional interface is an interface that has just one abstract method (aside from the methods of Object), and thus represents a single function contract.
https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.8

**Comment by winterbe** [comment]
Thanks for your input. Feel free to send a PR.
