### ISSUE TITLE
"Extension Methods"

### ISSUE THREAD

**Issue by spencerwi** [winterbe/java8-tutorial#7]
From the "Default Methods for Interfaces" section:

>Java 8 enables us to add non-abstract method implementations to interfaces by utilizing the default keyword. This feature is also known as **Extension Methods.**

This is inaccurate; I cannot, for instance, add a method `foo()` to String that could be called like so:

```java
String something = "bar";
something.foo();
"something else".foo();
```

Default methods on interfaces are more analogous to methods inherited from an abstract class than they are to [extension methods](https://en.wikipedia.org/wiki/Extension_method), which are "[methods] added to an object *after* the original object was compiled".

You can't actually add methods to any given object after it's compiled, because you can't change the interfaces which it declares that it implements. You also can't change an interface after it's compiled, and because of how interfaces work in Java, the interface must be compiled before the class. So if you don't control the class, you necessarily don't control the interface, and so you can't really add methods to any objects of that class after it's compiled.

**Comment by naasir** [comment]
+1. Totally agree with @spencerwi. Calling them extension methods is misleading. If you want to make a reference to something, I would say an interface with default implementations is similar to the concept of a [Trait](http://docs.scala-lang.org/tutorials/tour/traits.html) in Scala.

**Comment by winterbe** [comment]
I wrote the original article two years ago when java 8 was released. Default interface methods were officially stated as Extension Method by Oracle java folks. Let me check tomorrow if I can still find the cite.

**Comment by winterbe** [comment]
Couldn't find the cite in the official docs anymore, so maybe they've removed to prevent confusion. However Brian Goetz (Java Language Architect) calls default methods **virtual extension methods**, see: http://stackoverflow.com/a/24102730

I've corrected the README and put a link for clarifications. Thank you guys for pointing that out! :+1:
